# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Establishments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Role', models.CharField(choices=[('Manager', 'Manager'), ('Desk', 'Desk'), ('Help/Support', 'Help/Support')], max_length=50)),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Establishments.Theatre')),
            ],
        ),
    ]
