# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Establishments', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
