# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Establishments', '0003_establishment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='city',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theatre',
            name='location',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
