# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='meta_completed',
            field=models.BooleanField(default=False),
        ),
    ]
