# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie_meta',
            name='movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.FileField(upload_to=b''),
        ),
        migrations.DeleteModel(
            name='Movie_Meta',
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie'),
        ),
    ]
