# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 14:39
from __future__ import unicode_literals

from django.db import migrations,models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_movie_meta_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Establishments.Theatre'),
        ),
    ]
