# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20161022_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='role',
            new_name='character_name',
        ),
    ]
