# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 06:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_shows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField(default=datetime.datetime(2016, 11, 7, 11, 50, 26, 926000))),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
            ],
        ),
        migrations.RemoveField(
            model_name='shows',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Shows',
        ),
    ]
