# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_auto_20161107_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('seat_no', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 0, 5, 45, 340000)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Show'),
        ),
    ]
