# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_auto_20161108_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 0, 20, 5, 628000)),
        ),
    ]
