# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0015_auto_20161108_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 17, 9, 57, 953000)),
        ),
    ]
