# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Establishments', '0002_employee'),
        ('Movies', '0017_auto_20161109_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='theatre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Establishments.Theatre'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 18, 53, 49, 499000)),
        ),
    ]
