# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Establishments', '0006_theatre_city'),
        ('Movies', '0020_auto_20161113_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='theatre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Establishments.Theatre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 13, 19, 44, 19, 427000)),
        ),
    ]
