# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0026_auto_20161113_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='show_time',
        ),
    ]
