# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 22:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0027_remove_show_show_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='show_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
