# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:38
from __future__ import unicode_literals


from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0029_auto_20161113_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='max_no_seats',
            field=models.IntegerField(default=0),
        ),

    ]
