# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0030_auto_20161114_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_no',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
