# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 01:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0031_auto_20161115_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_no',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(49), django.core.validators.MinValueValidator(1)]),
        ),
    ]
