# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0033_auto_20161115_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=250.0),
        ),
    ]
